<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DekhBhai.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="10.0.16" />
    <PackageReference Include="SIPSorceryMedia.Abstractions" Version="10.0.16" />
    <PackageReference Include="SIPSorceryMedia.FFmpeg" Version="10.0.16" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Concentus" Version="2.2.2" />
  </ItemGroup>

</Project>
